resolver: lts-10.6
packages:
- .

extra-deps:
- git: https://github.com/AccelerateHS/accelerate.git
  commit: HEAD
- git: https://github.com/AccelerateHS/accelerate-llvm.git
  commit: HEAD
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
- git: https://github.com/tmcdonell/accelerate-blas.git
  commit: HEAD

flags:
  accelerate:
    debug: true
  accelerate-blas:
    llvm-ptx: false
